apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes.github.io/autoscaler
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: cluster-autoscaler
spec:
  interval: 5m
  chart:
    spec:
      chart: autoscaler/cluster-autoscaler
      version: '9.18.0'
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    autoDiscovery.clusterName: dev-cluster