---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: cluster-autoscaler
spec:
  chart:
    spec:
      chart: cluster-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: autoscaler
      version: 9.18.0
  interval: 1m0s
  releaseName: cluster-autoscaler
  values:
    autoDiscovery:
      clusterName: dev-cluster
    cloudProvider: aws
    awsRegion: eu-west-2
    autoscalingGroups: [0]
      - name: dev-cluster-asg
        maxSize: 3
        minSize: 1 
    rbac:
      create: true
      serviceAccount:
        create: true
        automountServiceAccountToken: true
    replicaCount: 1