---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: cluster-autoscaler
spec:
  chart:
    spec:
      chart: autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: autoscaler
      version: 9.18.0
  interval: 1m0s
  releaseName: cluster-autoscaler
  values:
    replicaCount: 1
    autoDiscovery:
      clusterName: dev-cluster