apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - clusterrole.yaml
  - clusterroleblinding.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml