---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: 3.8.2
  interval: 1m0s
  releaseName: metrics-server
  values:
    serviceAccount:
      create: true
    rbac:
      create: true
    hostNetwork: false
    replicas: 1
    metrics:
      enabled: false
