apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app
  labels:
    app: 2048-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
      - name: 2048-app
        image: {{ default "docker.io/evilroot/docker-2048:latest" .Values.image }}
        ports:
        - containerPort: 8080