apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      version: 34.7.0
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    alertmanager:
      enabled: false
    grafana:
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux
  grafana:  
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: 'true'
        cert-manager.io/cluster-issuer: letsencrypt
        cert-manager.io/duration: 2160h # 90d
        cert-manager.io/renew-before: 360h # 15d
        external-dns.alpha.kubernetes.io/hostname: grafana.anhtran.be
      tls:
      - secretName: grafana-general-tls
        hosts:
        - grafana.anhtran.be
      hosts: grafana.anhtran.be
      path: /
