---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus-monitoring-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/duration: 2160h # 90d
    cert-manager.io/renew-before: 360h # 15d
    external-dns.alpha.kubernetes.io/hostname: monitoring.anhtran.be
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - monitoring.anhtran.be
    secretName: issuer-sec
  rules:
    - host: monitoring.anhtran.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: prometheus-monitoring-service
              servicePort: 80
