---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.1.0
  interval: 1m0s
  releaseName: ingress-nginx
  values:
    service:
      type: LoadBalancer
    containerPort:
      http: 80
      https: 443
    controller:
      hostname: wide-load-balancer-a90664b19744a850.elb.eu-west-2.amazonaws.com
