---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flux-system
        namespace: flux-system
      version: 1.9.0
  interval: 1m0s
  releaseName: external-dns
  values:
    serviceAccount:
      create: true
    rbac:
      create: true
    service:
      port: 7979
    sources:
      - service
      - ingress
    provider: aws
    txtOwnerId: "external-dns"
