---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 1.9.0
  interval: 1m0s
  releaseName: external-dns
  values:
    serviceAccount:
      create: true
      annotations: {
        arn:aws:iam::063825035012:policy/AmazonEKS_External_DNS_Policy-20220510110710230900000001
        }
      name: "External-DNS"
    rbac:
      create: true
    service:
      port: 7979
    sources:
      - service
      - ingress-nginx
    provider: aws
