apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2048
  labels:
    app: app-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2048
  template:
    metadata:
      labels:
        app: app-2048
    spec:
      containers:
      - image: docker.io/rorymcleanaderas/docker-2048:latest
        name: app-2048
        ports:
        - containerPort: 80
      - command:
        - --rootpath=/usr/share/nginx/html
            