apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/scheme: internet-facing
    certmanager.k8s.io/cluster-issuer: selfsigned-cluster-issuer
    external-dns.alpha.kubernetes.io/hostname: 2048.anhtran.be
  name: app-2048
  namespace: app-2048
spec:
  tls:
    - hosts:
        - 2048.anhtran.be
    rules:
    - host: 2048.anhtran.be
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-2048-service
              port:
                number: https
                
