apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-2048-ingress
  namespace: app-2048
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: selfsigned-cluster-issuer
    kubernetes.io/ingress.class: ingress-nginx
spec:
  rules:
  - host: 2048.anhtran.be
    http:
      paths:
      - path: /usr/share/nginx/html
        pathType: Prefix
        backend:
          service:
            name: app-2048-service
            port:
              name: http