apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-2048-ingress
  namespace: app-2048
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: selfsigned-issuer
spec:
  rules:
  - host: anhtran.be
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-2048-service
            port:
              name: http