---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-2048-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    external-dns.alpha.kubernetes.io/hostname: app.anhtran.be
spec:
  ingressClassName: nginx
  rules:
    - host: app.anhtran.be
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              serviceName: app-2048-service
              servicePort: 8080
  tls:
    - hosts:
        - app.anhtran.be