---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-2048-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: anhtran-be-ca
    cert-manager.io/duration: 2160h # 90d
    cert-manager.io/renew-before: 360h # 15d
    external-dns.alpha.kubernetes.io/hostname: app.anhtran.be
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.anhtran.be
    secretName: anhtran-be-key-pair
  rules:
    - host: app.anhtran.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: app-2048-service
              servicePort: 80
