---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-2048-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/hostname: app.anhtran.be
spec:
  ingressClassName: nginx
  rules:
    - host: app.anhtran.be
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              serviceName: app-2048-service
              servicePort: 8181
