apiVersion: v1
kind: Service
metadata:
  name: app-2048-service
  namespace: app-2048
spec:
  selector:
    name: app-2048
  type: ClusterIP
  ports:
    - name: http
      port: 8181
      targetPort: http
      protocol: TCP



