apiVersion: v1
kind: Service
metadata:
  name: app-2048
  namespace: app-2048
  annotations:
    external-dns.alpha.kubernetes.io/hostname: 2048.anhtran.be
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: app-2048