apiVersion: v1
kind: Service
metadata:
  name: app-2048
  labels:
    app: app-2048
    service: app-2048
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: app-2048
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-2048-sa