apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yaml
  - repository.yaml
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: "issuer.yaml"
  prune: true
