---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.8.0
  interval: 1m0s
  releaseName: cert-manager
  values:
    global:
      rbac:
        create: true
        aggregateClusterRoles: true
      leaderElection:
        namespace: "flux-system"
    installCRDs: true
    replicaCount: 1
    serviceAccount:
      create: true
      automountServiceAccountToken: true
    prometheus:
      enabled: false