apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager-controller
  chart:
    spec:
      chart: cert-manager-controller
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "1.8.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  values:
    leaderElection:
      namespace: "flux-system"
    prometheus:
      enabled: false
