apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2048app-ingress
  annotations:
    cert-manager.io/issuer: 2048app-issuer
spec:
  tls:
  - hosts: [] # hosts will be added in another patch
    secretName: 2048app-cert