apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../bases/2048app

namespace: 2048app

patchesStrategicMerge:
- ingress.yaml

# Create this patch to set the Ingress domain
patchesJSON6902:
- path: ingress_patch.json
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: 2048app-ingress

configurations:
- cert-manager-configuration.yaml