---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- cert-manager
  - external-dns
  - nginx
  # - metrics-server - overlap with kube prometheus stack
  #- kube-prometheus-stack
  #- cluster-autoscaler - overlap with tf autoscaler