apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: anh@anhtran.be
    privateKeySecretRef:
      name: letsencrypt-sec
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster
  namespace: cert-manager
spec:
  acme:
    email: anh@anhtran.be
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: letsencrypt-cluster-sec
    solvers:
    - http01:
        ingress:
          class: nginx
